import { createSystem, defaultConfig } from "@chakra-ui/react";

export const system = createSystem(defaultConfig, {
  theme: {
    tokens: {
      colors: {
        primary: {
          50: { value: "#fff5e0" },
          100: { value: "#ffe4a8" },
          200: { value: "#ffd470" },
          300: { value: "#ffc338" },
          400: { value: "#ffb510" },
          500: { value: "#FF9F1C" },
          600: { value: "#e08a0e" },
          700: { value: "#b06b06" },
          800: { value: "#804d00" },
          900: { value: "#503000" },
          950: { value: "#281800" },
        },
        secondary: {
          50: { value: "#ffe8e8" },
          100: { value: "#ffbaba" },
          200: { value: "#ff8c8c" },
          300: { value: "#ff5e5e" },
          400: { value: "#FF4040" },
          500: { value: "#FF4040" },
          600: { value: "#e02020" },
          700: { value: "#b01818" },
          800: { value: "#801010" },
          900: { value: "#500808" },
          950: { value: "#280404" },
        },
        tertiary: {
          50: { value: "#e0faf5" },
          100: { value: "#a8f0e0" },
          200: { value: "#70e6cb" },
          300: { value: "#38dcb6" },
          400: { value: "#2EC4B6" },
          500: { value: "#2EC4B6" },
          600: { value: "#24a89c" },
          700: { value: "#1a8878" },
          800: { value: "#106854" },
          900: { value: "#084830" },
          950: { value: "#042818" },
        },
        dark: { value: "#0A1014" },
        grey: { value: "#1B2329" },
        midGrey: { value: "#353F4C" },
        lightGrey: { value: "#7A8C99" },
      },
      fonts: {
        heading: { value: "'Poppins', sans-serif" },
        body: { value: "'Poppins', sans-serif" },
      },
    },
    semanticTokens: {
      colors: {
        primary: {
          solid: { value: "{colors.primary.500}" },
          contrast: { value: "#FFFFFF" },
          fg: { value: "{colors.primary.600}" },
          muted: { value: "{colors.primary.200}" },
          subtle: { value: "{colors.primary.100}" },
          emphasized: { value: "{colors.primary.300}" },
          focusRing: { value: "{colors.primary.500}" },
        },
        secondary: {
          solid: { value: "{colors.secondary.500}" },
          contrast: { value: "#FFFFFF" },
          fg: { value: "{colors.secondary.600}" },
          muted: { value: "{colors.secondary.200}" },
          subtle: { value: "{colors.secondary.100}" },
          emphasized: { value: "{colors.secondary.300}" },
          focusRing: { value: "{colors.secondary.500}" },
        },
        tertiary: {
          solid: { value: "{colors.tertiary.500}" },
          contrast: { value: "#FFFFFF" },
          fg: { value: "{colors.tertiary.600}" },
          muted: { value: "{colors.tertiary.200}" },
          subtle: { value: "{colors.tertiary.100}" },
          emphasized: { value: "{colors.tertiary.300}" },
          focusRing: { value: "{colors.tertiary.500}" },
        },
      },
    },
  },
});
